// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import { EmitContext } from '@typespec/compiler';
import { Output, SourceFile } from '@alloy-js/core';
import { writeOutput } from '@typespec/emitter-framework';
import { GraphDocsEmitterOptions } from './lib.js';

export { $lib } from './lib.js';

export async function $onEmit(context: EmitContext<GraphDocsEmitterOptions>) {
  if (context.program.compilerOptions.noEmit) {
    return;
  }

  // TODO: Collect types and render pages (Phase 2-5)
  await writeOutput(
    context.program,
    <Output>
      <SourceFile path='README.md' filetype='md'>
        {
          '# API Reference\n\nGenerated by @microsoft/typespec-graph-docs-emitter\n'
        }
      </SourceFile>
    </Output>,
    context.emitterOutputDir,
  );
}
